---
- name: Install required system packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
    state: present
    update_cache: yes
  become: true

- name: Create app user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    create_home: true
    system: true
  become: true

- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  become: true

- name: Install required Python packages
  pip:
    name:
      - streamlit
      - requests
      - pandas
      - numpy
    state: present
  become: true

- name: Copy application files
  copy:
    src: "files/app/"
    dest: "{{ app_dir }}/"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
  become: true

- name: Generate app_config.py from template
  template:
    src: app_config.j2
    dest: "{{ app_dir }}/app_config.py"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
  become: true

- name: Install systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/vectordb-app.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: service_file

- name: Reload systemd if service file changed
  systemd:
    daemon_reload: yes
  become: true
  when: service_file.changed

- name: Enable and start the VectorDB application service
  systemd:
    name: vectordb-app
    state: restarted
    enabled: yes
  become: true